### ISSUE TITLE
Documentazione

### ISSUE THREAD

**Issue by JohnnyLAmpAz** [JohnnyLAmpAz/smartmag#19]
# Documentazione

Fondamentalmente, andrebbe curata e redatta tutta la parte di documentazione. Usiamo questo _issue_ (ed eventualmente di nuovi) per organizzare le modifiche da apportare.

Sarebbe grandioso realizzarla sottoforma di documenti _Markdown_ (`.md`) in modo tale da favorire l'integrazione con _git_ e la preview su _GitHub_.

## UML

- [x] #25
- [x] Case use diagram
- [x] State diagram
- [x] Class diagram
- [x] Activity diagram
- [x] Component diagram

(da completare e aggiornare...)

# Documento finale

Per quanto riguarda il documento finale, gli argomenti che dovrà trattare sono i seguenti:

- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #34
- [x] #36
- [x] #35
- [x] #38
- [x] #39
- [x] #50
- [x] #51
- [x] PDF Documento finale

**Comment by DavideBrambilla98** [comment]
# Documento finale

Per quanto riguarda il documento, gli argomenti che dovrà trattare sono i seguenti:

- [ ] Project plan
- [ ] Software life cycle
- [ ] Configuration management
- [ ] People management and team organization
- [ ] Software quality
- [ ] Requirement engineering
- [ ] Modelling
- [ ] Sosftware architecture
- [ ] Software design
- [ ] Software testing
- [ ] Software maintenance

**Comment by JohnnyLAmpAz** [comment]
Documento finale fatto mettendo insieme i vari capitoli già creati.

[0e31d38](https://github.com/JohnnyLAmpAz/smartmag/commit/0e31d3879fcc66c406c2b1df69f82a8101f51a7c) closes
