### ISSUE TITLE
Gestione view Box (assegnamento prodotti)

### ISSUE THREAD

**Issue by MassimilianoGervasoni** [JohnnyLAmpAz/smartmag#20]
Bisogna decidere in quale modo assegnare i prodotti ai box e come gestire la modifica delle quantita (o un cambio prodotto); ci sono sostanzialmente 2 soluzioni: 

1. integrarlo nella view dei prodotti
2. creare una nuova view ad hoc

**Comment by MassimilianoGervasoni** [comment]
eravamo partiti con l'idea di farlo nella tabella prodotto ma secondo me andrebbe ad appesantirla troppo, credo quindi sia meglio fare una nuova view specifica. ditemi cosa ne pensate

**Comment by JohnnyLAmpAz** [comment]
Anche io sarei per fare una view a parte che gestirà

1. la modifica delle quantità di un box
2. l'assegnazione di un prodotto in certa quantità ad un box vuoto

**Comment by MassimilianoGervasoni** [comment]
piccolo aggiornamento, alla fine lo sto sviluppando in questo modo: 
- lista prodotti da cui scegli e aggiungi indicando un box e una quantitá  -> controllo esistenza box :  -> se non esiste viene creato ; se esiste ed é vuoto viene cambiato prodotto ; se esiste e non é vuoto errore (e quindi implementanto nella view prodotti, ma si puo anche spostare in box volendo)                                                                                                    -
- lista di box da cui poter accedere a info del box e modificare quantitá (nuova view box)
- ricerca box in cui é presente un prodotto (pensavo semplicemente inserendo id prodotto in una barra che filtra la lista dei box)
