### ISSUE TITLE
Gestione view ordini

### ISSUE THREAD

**Issue by DavideBrambilla98** [JohnnyLAmpAz/smartmag#21]
Bisogna decidere come gestire la parte di inserimento nei prodotti all'interno di un ordine.

La soluzione attuale consiste nel generare un nuovo ordine partendo dai valori inseriti all'interno di un JDialog.
Nel JDialog, oltre a id, stato, tipo e le date, viene visualizzato un elenco di prodotti, dal quale si può scegliere un prodotto col quale creare l'ordine.
Come possiamo inserire altri prodotti nell'ordine appena creato?

**Comment by MassimilianoGervasoni** [comment]
non si riesce a fare tipo un button "Aggiungi Prodotto" che utilizzando la stessa tabella di prodotti permette di selezionarne uno e aggiungerlo all'ordine (passando per esempio l'id dell ordine, o direttamente aprendo l'ordine e usando direttamente il bottone da dentro) ?

**Comment by JohnnyLAmpAz** [comment]
Riutilizzare la tabella di prodotti per la scelta è una buona idea ma anche la combobox che stavi facendo ci sta. In ogni caso bisogna anche creare una sorta di tabella

| prodotto | quantità |
| - | - |
|ID 1|3|

che mostra la lista della spesa man mano che si selezionano i prodotti.
