### ISSUE TITLE
Richiesta approvazione Project Plan

### ISSUE THREAD

**Issue by JohnnyLAmpAz** [JohnnyLAmpAz/smartmag#4]
Alla cortese attenzione dei Professori del corso di Ingegneria del Software,

chiediamo l'approvazione del _Project Plan_ in allegato e presente nella repository sotto la cartella `./docs`.

[SmartMag_ProjectPlan.pdf](https://github.com/JohnnyLAmpAz/ingsw_proj_magazzino/files/13928812/SmartMag_ProjectPlan.pdf)

**Comment by garganti** [comment]
Non ho capito bene cosa sia una squadra  AGILE .. noi abbiamo fatto la squadra SCRUM ma non penso che sia il vostro caso, mi sembra più ognuno fa tutto? Magari dividetevi un po' le responsabilità, tipo matrice ... giusto per organizzare il lavoro.
Buon lavoro
