### ISSUE TITLE
voto progetto

### ISSUE THREAD

**Issue by garganti** [JohnnyLAmpAz/smartmag#52]
ottimo progetto, con ottimo uso di github.
per l'architettura a 3 livelli potevate fare 3 progetti separati (vi avrebbe aiutato ad organizzare il codice)
--> 4.8

**Comment by JohnnyLAmpAz** [comment]
Vista la verbalizzazione del voto, La ringraziamo per la valutazione e le auguriamo una serena Pasqua.

Cordiali saluti

Davide, Lorenzo e Massimiliano
